dummyproject/base/urls.py
"""Base url configurations."""
from django.urls import path
from .views import (LandingPageTemplateView,
                    BasicDemoTemplateView)

app_name = "base"

urlpatterns = [
    path('', LandingPageTemplateView.as_view(), name="index"),
    # elements
    path('basic-demo', BasicDemoTemplateView.as_view(), name="basic-demo"),
]

dummyproject/dummyproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

dummyproject/base/models.py
from django.db import models

# Create your models here.

dummyproject/base/views.py
"""Base views."""
# from django.shortcuts import render
from django.views.generic import (TemplateView)


class LandingPageTemplateView(TemplateView):
    """Landing Page TemplateView."""

    template_name = "base/index.html"


class BasicDemoTemplateView(TemplateView):
    """Landing Page TemplateView."""

    template_name = "base/elements/basic-demo.html"

dummyproject/base/templates/base/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %}</title>

    {% block js_head %}
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}

    {% block js_footer %}
    {% endblock %}
</body>
</html>

dummyproject/base/templates/base/elements/basic-demo.html
{% load static %}
<link rel="import" href="{% static 'polymer/polymer-element.html' %}">

<dom-module id="basic-demo">
  <template>
    <style>
      :host {
        display: block;
      }
    </style>
    <h2>Hello [[prop1]]!</h2>
  </template>

  <script>
    /**
     * `bbc-minute`
     * A bbc element to feature the globalnewsbeat
     *
     * @customElement
     * @polymer
     * @demo demo/index.html
     */
    class BasicDemo extends Polymer.Element {
      static get is() { return 'basic-demo'; }
      static get properties() {
        return {
          prop1: {
            type: String,
            value: 'Basic Demo'
          }
        };
      }
    }

    window.customElements.define(BasicDemo.is, BasicDemo);
  </script>
</dom-module>

dummyproject/base/templates/base/index.html
{% extends 'base/base.html' %}

{% block title %}Welcome{% endblock %}



{% block js_head %}
{% load static %}
<script src="{% static 'webcomponentsjs/webcomponents-loader.js' %}"></script> 

<link rel="import" href="{% static 'polymer/polymer.html' %}">
<link rel="import" href="{% static 'iron-demo-helpers/demo-pages-shared-styles.html' %}">
<link rel="import" href="{% static 'iron-demo-helpers/demo-snippet.html' %}">
<link rel="import" href="{% url 'base:basic-demo' %}">
{% endblock %}


{% block body %}
<custom-style>
<style is="custom-style" include="demo-pages-shared-styles"></style>
</custom-style>

<div class="vertical-section-container centered">
  <h3>Basic Demo</h3>
  <demo-snippet>
  <template>
      <basic-demo></basic-demo>
  </template>
</demo-snippet>
</div>

{% endblock %}